[web]
184.72.108.75
<<<<<<< HEAD
=======


[localhost]
localhost

[localhost:vars]
Course= "ansible from Inventory"
Platform= "JoinDevops"
Duration= "2.5 months"
  
>>>>>>> 5c1e03d (upload file in repo)
